# Generated by Django 6.1.1 on 2026-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones internas del ítem en inventario.'),
        ),
    ]
