# Generated by Django 6.1.1 on 2026-09-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_stock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='notas',
            field=models.TextField(blank=True, help_text='Ej. rolls incluidos/quitados en una tabla personalizada.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ceviches', 'Ceviches'), ('picoteo', 'Algo para picar'), ('papas', 'Papas fritas'), ('shawarmas', 'Shawarmas'), ('tablas', 'Tablas'), ('gohan', 'Gohan'), ('agregados', 'Agregados'), ('sushi', 'Sushi'), ('shawarma', 'Shawarma'), ('bebestibles', 'Bebestibles')], max_length=20),
        ),
    ]
