# Generated by Django 6.1.1 on 2026-09-30 22:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_venta_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='total_webpay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('webpay', 'Webpay')], max_length=20),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=30)),
                ('tipo_entrega', models.CharField(choices=[('retiro', 'Retiro'), ('delivery', 'Delivery')], max_length=20)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('notas', models.TextField(blank=True, default='')),
                ('cobro_delivery', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('esperando_pago', 'Esperando pago'), ('pagado', 'Pagado'), ('recibido', 'Recibido'), ('rechazado', 'Rechazado')], default='esperando_pago', max_length=20)),
                ('buy_order', models.CharField(max_length=26, unique=True)),
                ('webpay_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('authorization_code', models.CharField(blank=True, default='', max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_web', to='pos.venta')),
            ],
            options={
                'verbose_name': 'pedido web',
                'verbose_name_plural': 'pedidos web',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='pos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.pedido')),
            ],
            options={
                'verbose_name': 'detalle de pedido',
                'verbose_name_plural': 'detalles de pedido',
            },
        ),
    ]
