# Generated by Django 6.1 on 2026-10-02 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_pedidos_webpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta débito'), ('credito', 'Tarjeta crédito'), ('transferencia', 'Transferencia'), ('webpay', 'Webpay')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pos.venta')),
            ],
            options={
                'verbose_name': 'pago de venta',
                'verbose_name_plural': 'pagos de venta',
            },
        ),
    ]
