# Generated by Django 6.1 on 2026-10-02 21:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_pagoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='total_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='total_debito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
