# Generated by Django 6.1 on 2026-10-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_cajadiaria_total_credito_cajadiaria_total_debito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['nombre'], 'verbose_name': 'inventario', 'verbose_name_plural': 'inventarios'},
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de unidades disponibles.'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(default='', help_text='Nombre del empaque.', max_length=150),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones internas del empaque.'),
        ),
    ]
